test:
  site_url: 127.0.0.1:3000
  site_name: EuRuKo_test
  admin_email: euruko_test@euruko2009.org
    
development:
  site_url: 127.0.0.1:3000
  site_name: EuRuKo_development
  admin_email: euruko_development@euruko2009.org
      
production:
  site_url: eurukostaging.fernandoguillen.info
  site_name: EuRuKo
  admin_email: euruko@euruko2009.org
  